use_frameworks!

target 'SocialLoginKit_Example' do
    pod 'SocialLoginKit/Facebook', :path => '../'
    pod 'SocialLoginKit/Naver', :path => '../'
    pod 'SocialLoginKit/Kakao', :path => '../'
    
  target 'SocialLoginKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
